config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'comments/create'
  resources :posts
  resources :benefits
  resources :users_admin, :controller => 'users' 

  resources :users_admin do
    collection do
      patch 'admin_actions'
    end
  end


  get 'pages/lock'
  get 'pages/user_compaigns'
  get 'pages/user_supported'
  get 'compaigns/support'
  get '/compaigns/:id/posts', to: 'compaigns#posts', as: 'updates'
  patch 'compaigns/update_current_sum'
  
  resources :compaigns do
    # post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end

  root to: 'compaigns#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :compaign
  validates :body, presence: true, allow_blank: false

  after_create_commit {
    CommentBroadcastJob.perform_later(self)
  }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_compaign

  def create
    @comment = @compaign.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def destroy
    @comment = @compaign.comments.find(params[:id])
    @comment_id = @comment.id
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :compaign_id)
  end

  def set_compaign
    @compaign = Compaign.find(params[:compaign_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class="comment mb-3">
  <div class="mb-2">
    <p class="m-0 p-0">By <%= comment.user.name %></p>
    <small class="text-muted"><%= comment.created_at.strftime("%Y.%m.%d, %R") %></small>
  </div>
  <div class="mb-2">
    <%= comment.body %>
  </div>
</div>

app/views/comments/_destroy.html.erb
<div class="mb-3 ml-3">
  <%= link_to "Delete comment", compaign_comment_path(@compaign, comment), method: :delete, remote: true, class: "text-success" %>
</div>

app/views/comments/create.js.erb
$('#comment_body').val('');
$(document.documentElement).scrollTop($(document.documentElement)[0].scrollHeight);
$("#comment_pane").append("<%= escape_javascript("#{render :partial => 'comments/destroy', :locals => { :comment => @comment }}").html_safe %>");

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').next().remove();
$('#comment-<%= @comment.id %>').remove();
$('#comments_count').html($('.comment').length);