config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'comments/create'
  resources :posts
  resources :benefits
  resources :users_admin, :controller => 'users' 

  resources :users_admin do
    collection do
      patch 'admin_actions'
    end
  end


  get 'pages/lock'
  get 'pages/user_compaigns'
  get 'pages/user_supported'
  get 'compaigns/support'
  get '/compaigns/:id/posts', to: 'compaigns#posts', as: 'updates'
  patch 'compaigns/update_current_sum'
  
  resources :compaigns do
    # post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end

  root to: 'compaigns#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/compaign.rb
class Compaign < ApplicationRecord
  belongs_to :user
  has_many :benefits, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  ratyrate_rateable "rating"
  has_one_attached :image
  validates :title, presence: true, length: { maximum: 135 } 
  validates :project_idea, presence: true, length: { maximum: 240 }
  validates :description, presence: true, length: { minimum: 42 }
  validates :goal, presence: true, numericality: true
  validate :correct_image_type

  YT_LINK_FORMAT = /(^$|\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([\A#\&\?]*).*)/i

  validates :video, format: YT_LINK_FORMAT

  def thumbnail
    return self.image.variant(resize: '800x800')
  end

  def card_image
    return self.image.variant(resize: '320x200!')
  end  

  private

  def correct_image_type
    if !image.attached?
      errors.add(:image, 'required.')
    elsif !image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:image, 'must be a JPEG or PNG.')
     end
  end

end

app/controllers/compaigns_controller.rb
class CompaignsController < ApplicationController
  before_action :set_compaign, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index, :posts] 
  before_action :locked?, except: [:show, :index]
  protect_from_forgery except: :index
  # GET /compaigns
  # GET /compaigns.json

  $categories = %w(Art Comics Crafts Dance Design Fashion Film&Video Food Games Journalism Music Photography Publishing Technology Theater)


  def index
    @compaigns = Compaign.with_attached_image.includes(:user).paginate(page: params[:page], per_page: 6)
    @user = current_user
  end

  def posts
    @user = current_user
    @compaign = Compaign.includes(:posts).find(params[:id])
  end

  # GET /compaigns/1
  # GET /compaigns/1.json
  def show
   @user = current_user
   @results = parse_video_url(@compaign.video)
   @comment = Comment.new
   @comments = @compaign.comments
  end

  def support
    @compaign = Compaign.find_by(id: request.params[:format])
  end

  def update_current_sum
    @compaign = Compaign.find_by(id: request.params[:format])
    @compaign.update_attribute(:current_sum, @compaign.current_sum + [0, params[:compaign][:current_sum].to_i].max)
    if params.keys[4] != "commit"
      current_user.update_attribute(:benefits, current_user.benefits << params.keys[4])
    end
    flash[:notice] = "Thanks for the help!"
    redirect_to @compaign
  end

  # GET /compaigns/new
  def new
    @compaign = Compaign.new
  end

  # GET /compaigns/1/edit
  def edit
  end

  # POST /compaigns
  # POST /compaigns.json
  def create
    @compaign = Compaign.new(compaign_params)
    @compaign.user = current_user
    respond_to do |format|
      if @compaign.save
        format.html { redirect_to new_benefit_url(@compaign), notice: 'Compaign was successfully created.' }
        format.json { render :show, status: :created, location: @compaign }
      else
        format.html { render :new }
        format.json { render json: @compaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compaigns/1
  # PATCH/PUT /compaigns/1.json
  def update
    respond_to do |format|
      if @compaign.update(compaign_params)
        format.html { redirect_to @compaign, notice: 'Compaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @compaign }
      else
        format.html { render :edit }
        format.json { render json: @compaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compaigns/1
  # DELETE /compaigns/1.json
  def destroy
    @compaign.destroy
    respond_to do |format|
      format.html { redirect_to compaigns_url, notice: 'Compaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def parse_video_url(url)
    @url = url

    youtube_formats = [
        %r(https?://youtu\.be/(.+)),
        %r(https?://www\.youtube\.com/watch\?v=(.*?)(&|#|$)),
        %r(https?://www\.youtube\.com/embed/(.*?)(\?|$)),
        %r(https?://www\.youtube\.com/v/(.*?)(#|\?|$)),
        %r(https?://www\.youtube\.com/user/.*?#\w/\w/\w/\w/(.+)\b)
      ]

    @url.strip!

    if @url.include? "youtu"
      youtube_formats.find { |format| @url =~ format } and $1
      @results = {provider: "youtube", id: $1}
      @results
    else
      return @results = nil # There should probably be some error message here
    end  
end

    def locked?
      redirect_to pages_lock_path if  current_user && current_user.locked
    end

    def set_compaign
      @compaign = Compaign.with_attached_image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compaign_params
      params.require(:compaign).permit(:title, :project_idea, :description, :goal, :endtime, :video, :category, :image, :current_sum)
    end
end

app/helpers/compaigns_helper.rb
module CompaignsHelper
end

app/views/compaigns/_form.html.erb
<div class="form form-compaign">
  <%= form_with(model: compaign, local: true) do |form| %>
<% if compaign.errors.any? %>
    <div class="alert alert-danger">
      <div id="error_explanation">
        <h2><%= pluralize(compaign.errors.count, "error") %> prohibited this compaign from being saved:</h2>

        <ul>
        <% compaign.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field mb-3">
    <div class="text-center">
      <%= form.label :title %>
    </div>
    <%= form.text_field :title, class: "form-control", placeholder: "maximum 135 characters" %>
  </div>

  <div class="field mb-3">
    <div class="text-center">
      <%= form.label :project_idea %>
    </div>
    <%= form.text_field :project_idea, class: "form-control", placeholder: "maximum 240 characters" %>
  </div>


  <div class="field mb-3">
    <div class="text-center">
      <%= form.label :description %>
    </div>
    <%= form.text_area :description, placeholder: "minimum 42 characters" %>
  </div>

  <div class="field mb-3">
    <div class="text-center"> 
      <%= form.label :goal %>
    </div>
    <%= form.text_field :goal, class: "form-control", placeholder: "amount in dollars" %>
  </div>

  <div class="field mb-3">
    <div class="text-center">
      <%= form.label :endtime %> <br>
      <%= form.datetime_select :endtime, prompt: { day: 'Select day', month: 'Select month', year: 'Select year'}, discard_hour: true, discard_minute: true, :start_year => Date.current.year, :end_year => Date.current.year + 100 %> 
    </div>
  </div>
  
  <div class="field mb-3">
    <div class="text-center mb-2">
      <span>Project image</span>
    </div>
    <div class="text-center">
    <%= form.drag_and_drop_file_field :image, 'Drop an image here, or select a file.' %>
      
    </div> 
  </div>  

  <div class="field mb-3">
    <div class="text-center">
      <%= form.label :video %>
    </div>
    <%= form.text_field :video, class: "form-control", placeholder: "URL for video (YouTube)" %>
  </div>

  <div class="field mb-3">
    <div class="text-center">
      <%= form.label :category %>
      <%= form.collection_select :category, $categories, :to_s, :to_s, include_blank: false %>      
    </div>
  </div>

  

  <div class="actions">
    <div class="text-center">
      <%= form.submit class: "btn btn-outline-success" %>
    </div>
  </div>
<% end %>

</div>

app/views/compaigns/_header.html.erb
<div class="text-center mb-3">
  <p>
    <h1><%= @compaign.title %></h1>
  </p>

  <p>
    <h4><%= @compaign.project_idea %></h4>
  </p>
  <hr>
</div>

app/views/compaigns/edit.html.erb
<h1 class="text-center">Editing Compaign</h1>

<%= render 'form', compaign: @compaign %>

<div class="text-center">
  <%= link_to 'Back', @compaign, class: "btn btn-outline-success btn-sm mb-5" %>
</div>

app/views/compaigns/index.html.erb
<div class="d-flex flex-wrap bd-highlight justify-content-center">
  <% @compaigns.each do |compaign|%>
    <div class="card bd-highlight m-3" style="width: 18rem;">
      <%= image_tag(compaign.card_image, class: "card-img-top") %>
      <div class="progress_bar mb-2">
          <div class="progress_bar_green" style="width: <%= (compaign.current_sum * 100)/compaign.goal %>%">
          </div>
        </div>
    <div class="card-body">
      <h5 class="card-title"><%= compaign.title %></h5>
      <p class="card-text"><%= compaign.project_idea %></p>
      <div class="badge badge-pill badge-success"><%= compaign.goal %> $</div>
      <br> <small class="text-muted">By <%= compaign.user.name %></small>

      <hr>
      <div class="d-flex flex-wrap bd-highlight justify-content-center">      
        <%= link_to 'Show', compaign, class: "btn btn-outline-success btn-sm mr-2" %>
        <% if @user && (@user.admin || @user.id == compaign.user_id) %>
            <%= link_to 'Edit', edit_compaign_path(compaign), class: "btn btn-outline-success btn-sm mr-2" %>
            <%= link_to 'Destroy', compaign, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-success btn-sm mr-2" %>
        <% end %>
      </div>
    </div>
    </div>
  <% end %>
</div>

<%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>

app/views/compaigns/new.html.erb
<h1 class="text-center">New Compaign</h1>

<%= render 'form', compaign: @compaign %>
<div class="text-center">
  <%= link_to 'Back', compaigns_path, class: "btn btn-outline-success btn-sm mb-5" %>
</div>

app/views/compaigns/posts.html.erb
<%= render 'header' %>

<h1 class="text-center mb-2">Posts</h1>
<div class="form-post">
<% @compaign.posts.with_attached_image.reverse_each do |post| %>
    <div class="post mb-4">
      <h5 class="text-center p-2"><%= post.title %></h5>
      <div class="text-center mb-2">
        <small class="text-muted"><%= post.created_at %></small>
      </div>
      <% if post.image.attached? %>
        <div class="image-frame">
          <%= image_tag(post.image) %>
        </div>
      <% end %>
      <p class="p-3"><%= truncate(post.description, length: 200) %></p>
      <div class="d-flex flex-wrap bd-highlight justify-content-center mb-3">
        <%= link_to 'Read more', post, class: "btn btn-outline-success btn-sm mr-2" %>

        <% if @user && (@user.admin || @user.id == @compaign.user_id) %>
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-outline-success btn-sm mr-2" %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-success btn-sm mr-2" %>

      <% end %>
    </div>
  </div>
<% end %>

<div class="text-center mb-5">
  <% if @user && (@user.admin || @user.id == @compaign.user_id) %>
    <%= link_to 'Create post', new_post_path(@compaign), class: "btn btn-outline-success btn-sm mb-2" %>
  <% end %>
  <br>
  <%= link_to "Back to compaign", @compaign, class: "btn btn-outline-success btn-sm" %>
  
</div>
</div>

app/views/compaigns/show.html.erb
<div class="text-center mb-5">
  <p>
    <h1><%= @compaign.title %></h1>
    <%= rating_for @compaign, 'rating', disable_after_rate: true, enable_half: true %>
  </p>

  <p>
    <h4><%= @compaign.project_idea %></h4>
  </p>

  <p>
    <span class="badge badge-success badge-pill"><%= @compaign.category %></span>
  </p>
  <hr>
</div>

<div class="row mb-5">
      <div class="col-lg-8">
        <div class="image-frame">
           <%= image_tag(@compaign.image) %>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="progress_bar mb-2">
          <div class="progress_bar_green" style="width: <%= (@compaign.current_sum * 100)/@compaign.goal %>%">
          </div>
        </div>
        <div><span class="current_sum">US$ <%= @compaign.current_sum %></span></div>
        <div class="mb-5">
          <small class="text-muted">pledged of US$ <%= @compaign.goal %> goal</small>  
        </div>
        <%= link_to 'Support the project', compaigns_support_path(@compaign), class: "btn btn-success btn-block" %>
        <%= link_to "Updates", updates_path(@compaign), class: "btn btn-outline-success btn-block mb-5" %>
        <small class="text-muted">This project will only be funded if it reaches its goal by <%= @compaign.endtime.strftime("%B %d, %Y") %>
        </small>        
        <div class="mt-5"><small class="text-muted">By <%= @compaign.user.name %></small></div>
       </div>
    </div>
<hr>
<div class="row">
  <div class="col-lg-8"> 
    <p>
    <h3 class="mb-4">About</h3>
      <%= markdown(@compaign.description) %>
    </p>

    <% if @compaign.video %>
      <% if @results == nil %>
        Invalid URL
        <% else %>
        <p>
          <iframe src='https://www.youtube.com/embed/<%= @results[:id] %>?rel=0&autoplay=0 %>' frameborder='0' allowfullscreen width="560" height="390"></iframe>
        </p>
      <% end %>
    <% end %>
    <div class="text-center">
    <% if @user && (@user.admin || @user.id == @compaign.user_id) %>
      <%= link_to 'Edit compaign', edit_compaign_path(@compaign), class: "btn btn-outline-success mb-2" %> <br>
    <% end %>
    <%= link_to 'Back', compaigns_path, class: "btn btn-outline-success btn-sm mb-5" %>
    </div>
    <hr>
    <h1 class="text-center">Comments (<span id="comments_count"><%= @compaign.comments.count %></span>)</h1>

    <div id="comment_pane" class="form form-comment">
      <% @comments.includes(:user).each do |comment|%>
        <%= render 'comments/comment', comment: comment %>
        <% if @user && (@user.admin || @user.id == comment.user_id) %>
          <%= render 'comments/destroy', comment: comment %>
        <% end %>
      <% end %>
    </div>

    <div class="form form-comment">
      <% if current_user %>
      <%= form_with model:[@compaign, @comment] do |f|%>
        <%= f.text_field :body, class: "form-control mb-3", placeholder: "Say something..." %>
        <%= f.submit "Comment", class: "btn btn-outline-success btn-block" %>
      <% end %>
    <% end %>
    </div>
  </div>


  <div class="col-lg-4">
    <p>
  <h3 class="mb-4">Support</h3>
  <% @compaign.benefits.each do |benefit| %>
    <div class="benefit mb-3">
      <h5>Pledge $<%= benefit.sum %> or more</h5>
        <div class="mb-2"><%= benefit.reward %></div>
        <div class="text-secondary mb-2"><%= benefit.description %></div>
        <div class="mb-2">
          <button class="btn-sm btn-outline-success btn-block btn support">Get it!</button>
          <div class="form-hide">
            <%= form_tag compaigns_update_current_sum_path(@compaign), method: :patch do %>

            <div class="field mb-3">
              <div class="text-center">
                <div class="d-flex flex-row">
                <%= number_field(:compaign, :current_sum, value: benefit.sum, class: "form-control" ) %>
                  <span class="p-2">$</span>
                </div>
              </div>
            </div>

            <div class="actions">
              <div class="text-center">
                <%= submit_tag "Support", class: "btn btn-outline-success", :name => benefit.id %>
              </div>
            </div>
          <% end %>
        </div>
        </div>
        
        <div class="text-center">
          <% if @user && (@user.id == @compaign.user_id || @user.admin) %>
          <%= link_to 'Edit', edit_benefit_path(benefit), class: "btn btn-sm btn-outline-success btn-block" %> 
          <%= link_to 'Destroy', benefit, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-success btn-block" %>
        <% end %>
        </div>
    </div>
  <% end %>
    </p>
    <% if @user && @user.email == @compaign.user.email %>
    <div class="text-center">
      <%= link_to 'Create another one benefit', new_benefit_path(@compaign), class: "btn btn-outline-success btn-sm" %>
    </div>
    <% end %>

  </div>
</div>

app/views/compaigns/support.html.erb
<%= render 'header' %>

<div class="text-center">
  <h1 class="mb-5">Support this project</h1>

<div class="text-center mb-3">
  <h5>Make a pledge without a reward</h5>
  <%= form_tag compaigns_update_current_sum_path(@compaign), method: :patch do %>

  <div class="field mb-3">
    <div class="text-center">
      <%= number_field(:compaign, :current_sum, value: 1, class: "form-control form-support d-inline") %>
      <span>$</span>      
    </div>
  </div>

  <div class="actions">
    <div class="text-center">
      <%= submit_tag 'Support', class: "btn btn-outline-success" %>
    </div>
  </div>
<% end %>
</div>
<div class="d-flex flex-wrap bd-highlight justify-content-center">

<% @compaign.benefits.each do |benefit| %>
    <div class="benefit mb-2 clcard m-2">
      <h5>Pledge $<%= benefit.sum %> or more</h5>
        <div class="mb-2"><%= benefit.reward %></div>
        <div class="text-secondary mb-2"><%= benefit.description %></div>
        <div class="text-center">
        <%= form_tag compaigns_update_current_sum_path(@compaign), method: :patch do %>

  <div class="field mb-3">
    <div class="text-center">
      <%= number_field(:compaign, :current_sum, value: benefit.sum ) %>      
    </div>
  </div>

  <div class="actions">
    <div class="text-center">
      <%= submit_tag "Support", class: "btn btn-outline-success", :name => benefit.id %>
    </div>
  </div>
<% end %>
        </div>
    </div>
  <% end %>
</div>
</div>