config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'comments/create'
  resources :posts
  resources :benefits
  resources :users_admin, :controller => 'users' 

  resources :users_admin do
    collection do
      patch 'admin_actions'
    end
  end


  get 'pages/lock'
  get 'pages/user_compaigns'
  get 'pages/user_supported'
  get 'compaigns/support'
  get '/compaigns/:id/posts', to: 'compaigns#posts', as: 'updates'
  patch 'compaigns/update_current_sum'
  
  resources :compaigns do
    # post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end

  root to: 'compaigns#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  serialize :benefits, Array
  has_many :compaigns, dependent: :destroy
  has_many :comments, dependent: :destroy
  ratyrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :admin?
  before_action :locked?

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def update
    @users = User.where(id: params[:users_ids])
    destroy if deleting?
    make_admin if make_admin?
    delete_admin if delete_admin?
    lock if lock?
    unlock if unlock?
    respond_to do |format|
      format.html { redirect_to users_admin_index_url }
      format.json { head :no_content }
    end
  end

  def show
    
  end

  def destroy
    redirect_to destroy_user_session_path if current_user && current_user == @users
    @users.destroy_all
  end

  def lock
    redirect_to destroy_user_session_path if current_user && current_user == @users
    update_value(:locked, lock?)
  end

  def unlock
    update_value(:locked, !unlock?)
  end

  def make_admin
    update_value(:admin, make_admin?)
  end

  def delete_admin
    update_value(:admin, !delete_admin?)
  end


  private

  def lock?
    params[:commit] == 'lock'
  end

  def update_value(column, value)
    @users.each {|user| user.update_attribute(column, value)}        
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :id)
  end

  def unlock?
    params[:commit] == 'unlock'    
  end

  def deleting?
    params[:commit] == 'delete'
  end

  def make_admin?
    params[:commit] == 'make admin'
  end

  def delete_admin?
    params[:commit] == 'delete admin'
  end

  def admin?
    if !current_user.admin
      redirect_to root_path
    end
  end

  def locked?
    redirect_to pages_lock_path if current_user.locked
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h2 class="text-center mb-3">Admin panel</h2>
<%= form_tag admin_actions_users_admin_index_path, method: :patch do %>
<div class="text-center mb-3">
  <div class="btn-group">
    <%= submit_tag "make admin", :class => 'btn btn-outline-success btn-sm' %>
    <%= submit_tag "delete admin", :class => 'btn btn-outline-success btn-sm' %>
  </div>
  <div class="btn-group">
    <%= submit_tag "lock", :class => 'btn btn-outline-success btn-sm' %>
    <%= submit_tag "unlock", :class => 'btn btn-outline-success btn-sm' %>
  </div>

  <%= submit_tag "delete", :class => 'btn btn-outline-danger btn-sm' %>
</div>
  <h2 class="text-center">Users</h2>
  <table class="table mb-3" data-page-size="31" data-filter=#filter>
    <thead>
      <tr>
        <th class="text-center"><button id="check_all" class="btn btn-sm btn-success">Check all</button></th>
        <th>Name</th>
        <th>Email</th>
        <th>Created at</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="text-center"><%= check_box_tag "users_ids[]", user.id, false, class: 'selectable' %></td>
          <td>
            <%= user.name %>
            <% if user.admin %>
            <span class="badge badge-pill badge-success ml-4">admin</span>
            <% end %>
            <% if user.locked%>
            <span class="badge badge-pill badge-danger ml-4">locked</span>
            <% end %>  
          </td>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<% end %>
<%= will_paginate @users, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center) %>