config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'comments/create'
  resources :posts
  resources :benefits
  resources :users_admin, :controller => 'users' 

  resources :users_admin do
    collection do
      patch 'admin_actions'
    end
  end


  get 'pages/lock'
  get 'pages/user_compaigns'
  get 'pages/user_supported'
  get 'compaigns/support'
  get '/compaigns/:id/posts', to: 'compaigns#posts', as: 'updates'
  patch 'compaigns/update_current_sum'
  
  resources :compaigns do
    # post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end

  root to: 'compaigns#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  belongs_to :compaign
  validates :reward, presence: true, length: { maximum: 135 } 
  validates :description, presence: true, length: { maximum: 135 }
  validates :sum, presence: true, numericality: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :compaign
  validates :body, presence: true, allow_blank: false

  after_create_commit {
    CommentBroadcastJob.perform_later(self)
  }

end

app/models/compaign.rb
class Compaign < ApplicationRecord
  belongs_to :user
  has_many :benefits, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  ratyrate_rateable "rating"
  has_one_attached :image
  validates :title, presence: true, length: { maximum: 135 } 
  validates :project_idea, presence: true, length: { maximum: 240 }
  validates :description, presence: true, length: { minimum: 42 }
  validates :goal, presence: true, numericality: true
  validate :correct_image_type

  YT_LINK_FORMAT = /(^$|\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([\A#\&\?]*).*)/i

  validates :video, format: YT_LINK_FORMAT

  def thumbnail
    return self.image.variant(resize: '800x800')
  end

  def card_image
    return self.image.variant(resize: '320x200!')
  end  

  private

  def correct_image_type
    if !image.attached?
      errors.add(:image, 'required.')
    elsif !image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:image, 'must be a JPEG or PNG.')
     end
  end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :compaign
    has_one_attached :image
    validates :title, presence: true, length: { maximum: 135 } 
    validates :description, presence: true, length: { minimum: 42 }

    validate :correct_image_type

    def thumbnail
      return self.image.variant(resize: '800x800')
    end

    private

  def correct_image_type
    if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:image, 'must be a JPEG or PNG.')
    end
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  serialize :benefits, Array
  has_many :compaigns, dependent: :destroy
  has_many :comments, dependent: :destroy
  ratyrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :current_user?
  def home
    if current_user && current_user.locked
      redirect_to pages_lock_path
    end
  end

  def user_supported
    @compaigns = Compaign.includes(:benefits)
    @user_benefits = Benefit.where(id: current_user.benefits)
  end

  private


  def current_user?
    redirect_to root_path if !current_user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :locked?
  before_action :have_compaigns?, except: [:show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @compaign = Compaign.includes(:posts).find_by(id: @post.compaign_id)
    @user = current_user
  end

  # GET /posts/new
  def new
    @post = Post.new
    $compaign_id_from_request = request.params[:format]
  end

  # GET /posts/1/edit
  def edit
    @user = current_user
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.compaign_id = $compaign_id_from_request

    respond_to do |format|
      if @post.save
        format.html { redirect_to updates_path(Compaign.find_by(id: @post.compaign_id)), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to updates_path(Compaign.find_by(id: @post.compaign_id)), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to updates_path(Compaign.find_by(id: @post.compaign_id)), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def have_compaigns?
      redirect_to root_path if current_user && current_user.compaigns.length == 0
    end

    def locked?
      redirect_to pages_lock_path if  current_user && current_user.locked
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/benefits_helper.rb
module BenefitsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/compaigns_helper.rb
module CompaignsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show mt-2" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectItransition</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Modak&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,400i,500,500i,700,700i&display=swap&subset=cyrillic,cyrillic-ext" rel="stylesheet">     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-turbolinks="false">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'LOWKICKSTARTER', root_path, class: "navbar-brand text-success ml-5"%>
      <form class="form-inline my-2 my-lg-0 ml-5">
        <input class="form-control mr-sm-2 col-form-label-sm" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success btn-sm my-2 my-sm-0" type="submit">Search</button>
      </form>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <% if !current_user %>
              <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-success btn-sm" %>
              <%= link_to 'Sign in', new_user_session_path, class: "btn btn-outline-success btn-sm" %>
            <% end %>
          </li>
          <li class="nav-item">
           <% if current_user %>
              <%= link_to 'Create compaign', new_compaign_path, class: "btn btn-outline-success btn-sm mr-5" %>
           <% end %>
          </li>
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="dropdown-toggle btn btn-outline-success btn-sm" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% if current_user.admin %>
                  <%= link_to 'Users', users_admin_index_path, class: "dropdown-item" %>
                <% end %>
                <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to 'My compaigns', pages_user_compaigns_path, class: "dropdown-item" %>
                <%= link_to 'My benefits', pages_user_supported_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/lock.html.erb
<h1>you are locked</h1>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>

app/views/pages/user_compaigns.html.erb
<h1 class="text-center m-3">My compaigns</h1>

<table data-toggle="table">
    <thead>
      <tr>
        <th data-sortable="true" data-field="id">#</th>
        <th data-sortable="true" data-field="title">Title</th>
        <th data-sortable="true" data-field="current_sum">Current sum, $</th>
        <th data-sortable="true" data-field="goal">Goal, $</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.compaigns.each_with_index do |compaign, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td>
            <%= compaign.title %> 
          </td>
          <td>
            <%= compaign.current_sum %>
          </td>
          <td>
            <%= compaign.goal %>
          </td>
          <td class="text-center"><%= link_to 'Show', compaign, class: "btn btn-outline-success btn-sm mr-2" %>
            <%= link_to 'Edit', edit_compaign_path(compaign), class: "btn btn-outline-success btn-sm mr-2" %>
            <%= link_to 'Destroy', compaign, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-success btn-sm mr-2" %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/pages/user_supported.html.erb
<h1 class="text-center m-3">Supported</h1>
<div class="d-flex flex-wrap bd-highlight justify-content-center">
<% @user_benefits.each do |benefit| %>
    <div class="benefit mb-2 clcard m-2">
      <h5 class="mb-2"><%= @compaigns.find_by(id: benefit.compaign_id).title %> </h5>
      <h5>$<%= benefit.sum %> or more</h5>
        <div class="mb-2"><%= benefit.reward %></div>
        <div class="text-secondary mb-2"><%= benefit.description %></div>
    </div>
  <% end %>
</div>